draw_config:
  dark_mode: auto
  shrink_wide_legends: 7
  footer_text: "Corne Choc 42-Key · github.com/ryderdavid/corne-choc-42"
  svg_extra_style: "rect.key { filter: drop-shadow(2px 2px 2px rgba(0,0,0,0.2)); }"
  glyph_urls:
    mdi: "https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg"
    tabler: "https://unpkg.com/@tabler/icons/icons/outline/{}.svg"

parse_config:
  qmk_keycode_map:
    KC_BSPC: "Bspc"
    KC_DEL: "Del"
    KC_ESC: "Esc"
    KC_ENT: "Ent"
    KC_SPC: "Spc"
    KC_TAB: "Tab"
    KC_CAPS: "Caps"
    KC_GRV: "`"
    KC_TILD: "~"
    KC_MINS: "-"
    KC_EQL: "="
    KC_LBRC: "["
    KC_RBRC: "]"
    KC_BSLS: "\\"
    KC_SCLN: ";"
    KC_QUOT: "'"
    KC_COMM: ","
    KC_DOT: "."
    KC_SLSH: "/"
    KC_EXLM: "!"
    KC_AT: "@"
    KC_HASH: "#"
    KC_DLR: "$"
    KC_PERC: "%"
    KC_CIRC: "^"
    KC_AMPR: "&"
    KC_ASTR: "*"
    KC_LPRN: "("
    KC_RPRN: ")"
    KC_UNDS: "_"
    KC_PLUS: "+"
    KC_LCBR: "{"
    KC_RCBR: "}"
    KC_PIPE: "|"
    KC_PGUP: "PgUp"
    KC_PGDN: "PgDn"
    KC_HOME: "Home"
    KC_END: "End"
    KC_UP: "↑"
    KC_DOWN: "↓"
    KC_LEFT: "←"
    KC_RGHT: "→"
    KC_VOLU: "Vol+"
    KC_VOLD: "Vol-"
    KC_MUTE: "Mute"
    KC_MPLY: "Play"
    KC_MNXT: "Next"
    KC_MPRV: "Prev"
    KC_BRIU: "Bri+"
    KC_BRID: "Bri-"
    KC_LSFT: "Sft"
    KC_RSFT: "Sft"
    KC_LCTL: "Ctl"
    KC_RCTL: "Ctl"
    KC_LALT: "Opt"
    KC_RALT: "Opt"
    KC_LGUI: "Cmd"
    KC_RGUI: "Cmd"
    KC_NO: ""
    KC_TRNS: ""
    QK_BOOT: "Boot"
    QK_RBT: "Reboot"
    CW_TOGG: "CapsWd"

  modifier_fn_map:
    left_ctrl: "Ctl"
    right_ctrl: "Ctl"
    left_shift: "Sft"
    right_shift: "Sft"
    left_alt: "Opt"
    right_alt: "Opt"
    left_gui: "Cmd"
    right_gui: "Cmd"
    keycode_combiner: "{mods}+{key}"
    mod_combiner: "{mod_1}+{mod_2}"
